### ISSUE TITLE
ZumoTests in sdk/xamarin/ios/test folder do not compile for device

### ISSUE THREAD

**Issue by tkaczmarczyk** [xamarin/azure-mobile-services#1]
The test project compiles properly and runs on simulator but fails to compile for device. 

The error message obtained is: 
ZumoQuery.Test.cs:29 - The type or namespace "MobileServiceTableQueryDescription" could not be found.

This is despite the fact that the type is clearly available in the referenced assembly Microsoft.Azure.Zumo.iOS and despite the facts that the IDE sees and can navigate to the type and the same code compiles properly for the simulator.

**Comment by ermau** [comment]
This appears to be a bug in MonoTouch itself not respecting [InternalsVisibleTo] when compiling to device. I've filed this issue here: https://bugzilla.xamarin.com/show_bug.cgi?id=10223

**Comment by ermau** [comment]
Or not..
