### ISSUE TITLE
No support for custom API's

### ISSUE THREAD

**Issue by aaronpowell** [xamarin/azure-mobile-services#12]
If you're creating a custom API in Azure mobile services there's no way with the client to query that API.

It's available in the source repo - https://github.com/WindowsAzure/azure-mobile-services/blob/master/sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/MobileServiceClient.cs#L299 so it'd be great to get this back in sync

**Comment by aaronpowell** [comment]
I'd be happy to provide a PR but I've noticed that the repo this was forked from has quite a lot of differences so I'm not sure where to start, just copy the code files or do a pull-and-merge from it

**Comment by ermau** [comment]
Hi @aaronpowell,

The Azure guys have setup a new base for Azure Mobile Services that we're currently in the process of rebasing on, hence both the long time this has been out of sync and the large number of differences. We hope to have it available shortly.

**Comment by aaronpowell** [comment]
Thanks @ermau. If you need anyone to test a pre-release of the new API let me know as I'm presently hacking it together myself :frowning:

**Comment by ermau** [comment]
Sure, we'll push it to the repository on a new branch soon while we put the finishing touches on before updating the component.

**Comment by aaronpowell** [comment]
Sweet, I’ll grab it when it’s live and give it a run ☺
