### ISSUE TITLE
DeleteAsync resulting task status is RanToCompletion after server responds with http error.

### ISSUE THREAD

**Issue by ignaciofuentes** [xamarin/azure-mobile-services#7]
I have tested this with FORBIDDEN and INTERNAL SERVER ERROR.

The task doesnt ever have its status set as Faulted, which makes it hard to track server failures on delete.

**Comment by ermau** [comment]
Can you verify that 79ba699c510 fixes this?

**Comment by ignaciofuentes** [comment]
Yes. Fixed.
