### ISSUE TITLE
Can't get azure-mobile-services Android sample to work

### ISSUE THREAD

**Issue by nirschachter** [xamarin/azure-mobile-services#8]
Hi I can't seem to compile the todo sample soulution, I get this error:
And I also can't find instructions for it

Error   17  Source file 'C:\Users\Nir\Downloads\azure-mobile-services-master\azure-mobile-services-master\sdk\xamarin\libs\Xamarin.Auth\src\Xamarin.Auth.Android\ActivityEx.cs' could not be opened ('Unspecified error ')  Microsoft.Azure.Zumo.Android
Error   8   Source file 'C:\Users\Nir\Downloads\azure-mobile-services-master\azure-mobile-services-master\sdk\xamarin\libs\Xamarin.Auth\src\Xamarin.Auth.Android\ActivityStateRepository.cs' could not be opened ('Unspecified error ') Microsoft.Azure.Zumo.Android
Error   1   Source file 'C:\Users\Nir\Downloads\azure-mobile-services-master\azure-mobile-services-master\sdk\xamarin\libs\Xamarin.Auth\src\Xamarin.Auth.Android\AndroidAccountStore.cs' could not be opened ('Unspecified error ') Microsoft.Azure.Zumo.Android
Error   2   Source file 'C:\Users\Nir\Downloads\azure-mobile-services-master\azure-mobile-services-master\sdk\xamarin\libs\Xamarin.Auth\src\Xamarin.Auth.Android\FormAuthenticatorActivity.cs' could not be opened ('Unspecified error ')   Microsoft.Azure.Zumo.Android
Error   14  Source file 'C:\Users\Nir\Downloads\azure-mobile-services-master\azure-mobile-services-master\sdk\xamarin\libs\Xamarin.Auth\src\Xamarin.Auth.Android\WebAuthenticatorActivity.cs' could not be opened ('Unspecified error ')    Microsoft.Azure.Zumo.Android
Error   5   Source file 'C:\Users\Nir\Downloads\azure-mobile-services-master\azure-mobile-services-master\sdk\xamarin\libs\Xamarin.Auth\src\Xamarin.Auth\Account.cs' could not be opened ('Unspecified error ') Microsoft.Azure.Zumo.Android
Error   15  Source file 'C:\Users\Nir\Downloads\azure-mobile-services-master\azure-mobile-services-master\sdk\xamarin\libs\Xamarin.Auth\src\Xamarin.Auth\AccountStore.cs' could not be opened ('Unspecified error ')    Microsoft.Azure.Zumo.Android
Error   3   Source file 'C:\Users\Nir\Downloads\azure-mobile-services-master\azure-mobile-services-master\sdk\xamarin\libs\Xamarin.Auth\src\Xamarin.Auth\Authenticator.cs' could not be opened ('Unspecified error ')   Microsoft.Azure.Zumo.Android
Error   6   Source file 'C:\Users\Nir\Downloads\azure-mobile-services-master\azure-mobile-services-master\sdk\xamarin\libs\Xamarin.Auth\src\Xamarin.Auth\AuthException.cs' could not be opened ('Unspecified error ')   Microsoft.Azure.Zumo.Android
Error   12  Source file 'C:\Users\Nir\Downloads\azure-mobile-services-master\azure-mobile-services-master\sdk\xamarin\libs\Xamarin.Auth\src\Xamarin.Auth\ExceptionEx.cs' could not be opened ('Unspecified error ') Microsoft.Azure.Zumo.Android
Error   10  Source file 'C:\Users\Nir\Downloads\azure-mobile-services-master\azure-mobile-services-master\sdk\xamarin\libs\Xamarin.Auth\src\Xamarin.Auth\FormAuthenticator.cs' could not be opened ('Unspecified error ')   Microsoft.Azure.Zumo.Android
Error   9   Source file 'C:\Users\Nir\Downloads\azure-mobile-services-master\azure-mobile-services-master\sdk\xamarin\libs\Xamarin.Auth\src\Xamarin.Auth\OAuth1.cs' could not be opened ('Unspecified error ')  Microsoft.Azure.Zumo.Android
Error   4   Source file 'C:\Users\Nir\Downloads\azure-mobile-services-master\azure-mobile-services-master\sdk\xamarin\libs\Xamarin.Auth\src\Xamarin.Auth\OAuth1Authenticator.cs' could not be opened ('Unspecified error ') Microsoft.Azure.Zumo.Android
Error   13  Source file 'C:\Users\Nir\Downloads\azure-mobile-services-master\azure-mobile-services-master\sdk\xamarin\libs\Xamarin.Auth\src\Xamarin.Auth\OAuth2Authenticator.cs' could not be opened ('Unspecified error ') Microsoft.Azure.Zumo.Android
Error   16  Source file 'C:\Users\Nir\Downloads\azure-mobile-services-master\azure-mobile-services-master\sdk\xamarin\libs\Xamarin.Auth\src\Xamarin.Auth\WebAuthenticator.cs' could not be opened ('Unspecified error ')    Microsoft.Azure.Zumo.Android
Error   7   Source file 'C:\Users\Nir\Downloads\azure-mobile-services-master\azure-mobile-services-master\sdk\xamarin\libs\Xamarin.Auth\src\Xamarin.Auth\WebEx.cs' could not be opened ('Unspecified error ')   Microsoft.Azure.Zumo.Android
Error   11  Source file 'C:\Users\Nir\Downloads\azure-mobile-services-master\azure-mobile-services-master\sdk\xamarin\libs\Xamarin.Auth\src\Xamarin.Auth\WebRedirectAuthenticator.cs' could not be opened ('Unspecified error ')    Microsoft.Azure.Zumo.Android

**Comment by zgramana** [comment]
Make sure that you do a --recursive clone.

**Comment by yys** [comment]
custom API ！！！！
